name: 'Run Python Script'
description: 'This action executes a Python script.'
inputs:
  secretKey:
    description: 'Secret key for processing'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout action repo # replace it with downloading the binary from some url
      uses: actions/checkout@v2
      with:
        repository: 'Hopper-dev/github-action'
        ref: main
        path: 'action-repo'

    - name: Docker build
      run: docker build -t my-java-app .
      shell: bash
      working-directory: action-repo

    - name: Docker run
      run: docker run $(printenv | awk -F= '{print "-e ", $1"="$2}' | xargs) my-java-app 
      shell: bash

#    - name: Run script
#      run: chmod +x ./action-repo/hello-linux && ./action-repo/hello-linux "${{ github.workspace }}"
#      shell: bash
#      env:
#        SECRET_KEY: ${{ inputs.secretKey }}
