name: 'Run Python Script'
description: 'This action executes a Python script.'
runs:
  using: 'composite'
  steps:
#    - name: Setup Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.11

    - name: Checkout action repo
      uses: actions/checkout@v2
      with:
        repository: 'Hopper-dev/github-action'
        ref: main
        path: 'action-repo'

    - name: Run script
      run: chmod +x ./action-repo/hello-linux && ./action-repo/hello-linux
      shell: bash
