name: 'Run Python Script'
description: 'This action executes a Python script.'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Checkout action repo
      uses: actions/checkout@v2
      with:
        repository: 'Hopper-dev/github-action'
        ref: main
        path: 'action-repo'

    - name: Check for compiled artifact
      run: ls -l target
      shell: bash

    - name: Install dependencies
      run: pip install -r action-repo/requirements.txt
      shell: bash

    - name: Run script
      run: python action-repo/main.py
      shell: bash
