name: 'Run Python Script'
description: 'This action executes a Python script.'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Check ls
      run: ls -la
      shell: bash

    - name: Check pwd
      run: pwd
      shell: bash

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Run script
      run: python main.py
      shell: bash
