name: 'Run Python Script'
description: 'This action executes a Python script.'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Checkout action repo
      uses: actions/checkout@v2
      with:
        repository: 'Hopper-dev/github-action'
        ref: 'v4.0.0'
        path: 'action-repo'

    - name: Check ls
      run: ls -la action-repo
      shell: bash

    - name: Install dependencies
      run: pip install -r action-repo/requirements.txt
      shell: bash
    - name: Run script
      run: python main.py
      shell: bash
